# config/kinematics.yaml

dual_arm:
  kinematics_solver: kris_kinematics_plugin/KrisKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5

left_arm:
  kinematics_solver: kris_kinematics_plugin/KrisKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5

right_arm:
  kinematics_solver: kris_kinematics_plugin/KrisKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5

head:
  kinematics_solver: kris_kinematics_plugin/KrisKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5
