controller_manager:
  ros__parameters:
    fake_joint_driver:
      type: fake_components/GenericSystem
      hardware_parameters:
        fake_sensor_commands: false
        state_following_offset: 0.0

fake_joint_controller:
  ros__parameters:
    joints:
      - f18
      - f19  
      - f28
      - f29
      - j31
      - j32
    interface_name: position