ros__parameters:
  default_velocity_scaling_factor: 0.01  # Reduce for testing
  default_acceleration_scaling_factor: 0.01

  joint_limits:
    # Right arm (from URDF)
    j11:
      has_position_limits: true
      # min_position: -1.571
      # max_position: 1.571
      min_position: -0.7
      max_position: 0.7
    j12:
      has_position_limits: true
      min_position: -1.22
      max_position: 0.105
    j13:
      has_position_limits: true
      min_position: -1.571
      max_position: 1.571
    j14:
      has_position_limits: true
      min_position: -1.0472
      max_position: 1.309
    j15:
      has_position_limits: true
      min_position: -1.57
      max_position: 1.57
    j16:
      has_position_limits: true
      min_position: -0.52
      max_position: 0.52
    j17:
      has_position_limits: true
      min_position: -1.571
      max_position: 1.571

    # Left arm (from URDF)  
    j21:
      has_position_limits: true
      min_position: -1.571
      max_position: 1.571
    j22:
      has_position_limits: true
      min_position: -0.105
      max_position: 1.22
    j23:
      has_position_limits: true
      min_position: -1.571
      max_position: 1.571
    j24:
      has_position_limits: true
      min_position: -1.0472
      max_position: 1.309
    j25:
      has_position_limits: true
      min_position: -1.57
      max_position: 1.57
    j26:
      has_position_limits: true
      min_position: -0.52
      max_position: 0.52
    j27:
      has_position_limits: true
      min_position: -1.571
      max_position: 1.571
    
    j31:
      has_position_limits: true
      min_position: -1.57
      max_position: 1.57
    j_32:
      has_position_limits: true
      min_position: -0.52
      max_position: 0.52