ros__parameters:
  default_velocity_scaling_factor: 0.1
  default_acceleration_scaling_factor: 0.1

  joint_limits:
    j11:
      # has_velocity_limits: true
      # max_velocity: 1.5
      # has_acceleration_limits: false
      has_velocity_limits: true
      max_velocity: 1.5
      has_acceleration_limits: true
      max_acceleration: 2.0
    j12:
      has_velocity_limits: true
      max_velocity: 1.5
      has_acceleration_limits: true
      max_acceleration: 2.0
    j13:
      has_velocity_limits: true
      max_velocity: 1.5
      has_acceleration_limits: true
      max_acceleration: 2.0
    j14:
      has_velocity_limits: true
      max_velocity: 1.5
      has_acceleration_limits: true
      max_acceleration: 2.0
    j15:
      has_velocity_limits: true
      max_velocity: 1.5
      has_acceleration_limits: true
      max_acceleration: 2.0
    j16:
      has_velocity_limits: true
      max_velocity: 1.5
      has_acceleration_limits: true
      max_acceleration: 2.0
    j17:
      has_velocity_limits: true
      max_velocity: 1.5
      has_acceleration_limits: true
      max_acceleration: 2.0

    j21:
      has_velocity_limits: true
      max_velocity: 1.5
      has_acceleration_limits: true
      max_acceleration: 2.0
    j22:
      has_velocity_limits: true
      max_velocity: 1.5
      has_acceleration_limits: true
      max_acceleration: 2.0
    j23:
      has_velocity_limits: true
      max_velocity: 1.5
      has_acceleration_limits: true
      max_acceleration: 2.0
    j24:
      has_velocity_limits: true
      max_velocity: 1.5
      has_acceleration_limits: true
      max_acceleration: 2.0
    j25:
      has_velocity_limits: true
      max_velocity: 1.5
      has_acceleration_limits: true
      max_acceleration: 2.0
    j26:
      has_velocity_limits: true
      max_velocity: 1.5
      has_acceleration_limits: true
      max_acceleration: 2.0
    j27:
      has_velocity_limits: true
      max_velocity: 1.5
      has_acceleration_limits: true
      max_acceleration: 2.0

    # These are unused or disabled:
    # f18:
    #   has_velocity_limits: false
    #   max_velocity: 0
    # f19:
    #   has_velocity_limits: false
    #   max_velocity: 0
    # f28:
    #   has_velocity_limits: false
    #   max_velocity: 0
    # f29:
    #   has_velocity_limits: false
    #   max_velocity: 0
    # j31:
    #   has_velocity_limits: false
    #   max_velocity: 0
    # j_32:
    #   has_velocity_limits: false
    #   max_velocity: 0