move_group:
  ros__parameters:
    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

    moveit_simple_controller_manager:
      controller_names:
        - dual_arm_controller
      dual_arm_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        joints:
          - j11
          - j12
          - j13
          - j14
          - j15
          - j16
          - j17
          - j21
          - j22
          - j23
          - j24
          - j25
          - j26
          - j27
