# This config file is used by ros2_control

controller_manager:
  ros__parameters:
    use_sim_time: false
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    dual_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

dual_arm_controller:
  ros__parameters:
    joints:
      - j11
      - j12
      - j13
      - j14
      - j15
      - j16
      - j17
      - j21
      - j22
      - j23
      - j24
      - j25
      - j26
      - j27

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    allow_nonzero_velocity_at_trajectory_end: true  # Important for smoother execution

    constraints:
      goal_time: 0.0
      stopped_velocity_tolerance: 0.01
      j11: {trajectory: 0.1, goal: 0.05}
      j12: {trajectory: 0.1, goal: 0.05}
      j13: {trajectory: 0.1, goal: 0.05}
      j14: {trajectory: 0.1, goal: 0.05}
      j15: {trajectory: 0.1, goal: 0.05}
      j16: {trajectory: 0.1, goal: 0.05}
      j17: {trajectory: 0.1, goal: 0.05}
      j21: {trajectory: 0.1, goal: 0.05}
      j22: {trajectory: 0.1, goal: 0.05}
      j23: {trajectory: 0.1, goal: 0.05}
      j24: {trajectory: 0.1, goal: 0.05}
      j25: {trajectory: 0.1, goal: 0.05}
      j26: {trajectory: 0.1, goal: 0.05}
      j27: {trajectory: 0.1, goal: 0.05}
