move_group:
  ros__parameters:
    planning_scene_monitor_options:
      name: planning_scene_monitor
      robot_description: robot_description
      robot_description_semantic: robot_description_semantic
      monitored_planning_scene_topic: /planning_scene
      publish_planning_scene: true
      publish_geometry_updates: true
      publish_state_updates: true
      publish_transforms_updates: true

    occupancy_map_monitor:
      plugin: occupancy_map_monitor/OccupancyMapMonitor
      sensors_yaml: config/sensors_3d.yaml
