<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>dynamixel_test_utils</name>
  <version>0.1.0</version>
  <description>Utility scripts for testing Dynamixel motors</description>
  <maintainer email="talsania@example.com">talsania</maintainer>
  <license>Apache License 2.0</license>

  <depend>dynamixel_sdk</depend>
  <depend>rclpy</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
